const endOfDay = [
  "Locker refund: 1. Action",
  "2. Authenticate user.",
  "3. Sign-in with username and password.",
  "4. X report",
  "5. X report for till",
  "6. Till 1 or 2",
  "7. Member locker refund figure",
  "8. Exit",
  "9. Cancel",
  "10. Exit",
  "11. Return to point of sale.",
  "12. Login",
  "13. Member locker refund",
  "14. Type in figure (step 7)",
  "15. Quantity",
  "16. Payments",
  "17. Cash it of",
  "18. Take receipt plus the amount of lockers money from till.",
  "19. Cash taking – Action.",
  "20. Authenticate User",
  "21. Login",
  "22. Cash takings.",
  "23. Take out the amount from the appropriate till.",
  "24. FLOAT there now should be £50.00 left in the till which is your float.",
  "25. Complete float sheet record, sign and then Give float, locker refund money plus receipt to Duty Manager.",
  "26. Record cash taking on the cash register sheet.",
  "27. Ensure figures match.",
  "28. EXIT – cash up till",
  "29. Yes",
  "30. Type in cash total in yellow box.",
  "31. Accept",
  "32. Receipts will print out.",
  "33. Double check receipt and cash register sheet match",
  "34. Till 2 exit point of sale",
  "35. Till 1 run end of day – yes",
  "36. Kill process – end and accept until list gone and menu comes up again.",
  "37. End of Day",
  "38. Receipt will print out and staple to cash sheets."
];

export default endOfDay;